version: '3'

services:
  web:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - redis

  redis:
    image: "redis:latest"
