version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - '6379:6379'  

  web:
       build: . 
       container_name: app
       ports:
           - "5000:5000" 
       volumes:
           - .:/app
       depends_on:
           - redis

  
